// Тур по диагностическим флагам V8: запускает subject.mjs под разными флагами
// и показывает выжимку из того, что движок рассказывает о себе.
//
// Запуск: node 00-setup/examples/flag-tour.mjs
//
// Никаких особых флагов самому туру не нужно: он поднимает дочерние процессы.
// Логи пишутся во временный каталог, чтобы не мусорить в репозитории.

import { spawnSync } from 'node:child_process';
import { mkdtempSync, readdirSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const subject = join(import.meta.dirname, 'subject.mjs');
const workdir = mkdtempSync(join(tmpdir(), 'v8-flag-tour-'));

function run(flags) {
  const result = spawnSync(process.execPath, [...flags, subject], {
    cwd: workdir,
    encoding: 'utf8',
    maxBuffer: 256 * 1024 * 1024,
  });
  const output = `${result.stdout ?? ''}${result.stderr ?? ''}`;
  return output.split('\n').filter((line) => line.length > 0);
}

function linesAfter(lines, pattern, count) {
  const start = lines.findIndex((line) => pattern.test(line));
  return start === -1 ? ['(совпадений нет)'] : lines.slice(start, start + count);
}

function shorten(line, limit = 118) {
  return line.length > limit ? `${line.slice(0, limit - 1)}…` : line;
}

// Адреса в куче занимают половину строки и меняются от запуска к запуску.
function stripAddresses(line) {
  return line
    .replace(/\s*\(sfi = 0x[0-9a-f]+\)/g, '')
    .replace(/\[\d+:0x[0-9a-f]+\]\s*/g, '')
    .replace(/0x[0-9a-f]+,?\s*/g, '');
}

const demos = [
  {
    title: 'Байткод одной функции',
    flags: ['--print-bytecode', '--print-bytecode-filter=add'],
    hint: 'Во что превращается `return a + b`. Фильтр обязателен: без него на экран выпадет весь Node.',
    select: (lines) => linesAfter(lines, /generated bytecode for function: add/, 10),
  },
  {
    title: 'Повышение уровня компиляции',
    flags: ['--trace-opt'],
    hint: 'Когда функция признана горячей и ушла в оптимизирующий компилятор.',
    select: (lines) =>
      lines
        .filter((line) => /JSFunction (add|readX) /.test(line))
        .slice(0, 6)
        .map(stripAddresses),
  },
  {
    title: 'Деоптимизация',
    flags: ['--trace-deopt'],
    hint: 'Спекуляция не подтвердилась: у readX встретился объект другой формы (wrong map).',
    select: (lines) =>
      lines
        .filter((line) => line.includes('bailout'))
        .map((line) => stripAddresses(line.replace(/, opt id.*$/, '')))
        .slice(0, 5),
  },
  {
    title: 'Сборка мусора',
    flags: ['--trace-gc'],
    hint: 'Каждая строка — одна пауза. Scavenge — молодое поколение, Mark-Compact — старое.',
    select: (lines) => {
      const gcLines = lines.filter((line) => /Scavenge|Mark-Compact|Mark-Sweep/.test(line));
      const scavenges = gcLines.filter((line) => line.includes('Scavenge')).length;
      const majors = gcLines.length - scavenges;
      return [
        ...gcLines.slice(0, 3).map(stripAddresses),
        `... всего сборок: ${gcLines.length} (Scavenge ${scavenges}, старшее поколение ${majors})`,
      ];
    },
  },
  {
    title: 'Inline caches в лог',
    flags: ['--log-ic'],
    hint: 'В консоль ничего не печатается: записи уходят в isolate-*.log рядом с процессом.',
    select: () => {
      const logs = readdirSync(workdir).filter((name) => name.endsWith('.log'));
      if (logs.length === 0) return ['(лог не найден)'];
      const path = join(workdir, logs[0]);
      const size = Math.round(statSync(path).size / 1024);
      return [
        `${logs[0]} — ${size} KB`,
        'Читать глазами бесполезно: лог обрабатывают tools/ic-processor из V8 или deoptigate.',
      ];
    },
  },
];

console.log(`\nПодопытный: ${subject}`);
console.log(`Рабочий каталог для логов: ${workdir}`);

for (const demo of demos) {
  const command = `node ${demo.flags.join(' ')} 00-setup/examples/subject.mjs`;
  console.log(`\n${demo.title}`);
  console.log('='.repeat(demo.title.length));
  console.log(`  ${demo.hint}`);
  console.log(`  $ ${command}\n`);
  for (const line of demo.select(run(demo.flags))) {
    console.log(`  ${shorten(line)}`);
  }
}

console.log('\nЧто посмотреть дальше');
console.log('=====================');
console.log('  --print-opt-code --print-opt-code-filter=add   машинный код после TurboFan');
console.log('  --trace-turbo                                  граф IR для Turbolizer');
console.log('  --cpu-prof                                     профиль в формате DevTools');
console.log('  --v8-options                                   все флаги этой сборки');
console.log('\n  Полная шпаргалка — в flags-cheatsheet.md\n');

rmSync(workdir, { recursive: true, force: true });
