// Проверка лабы: каждый набор флагов проверяется по наблюдаемому эффекту,
// а не сравнением строк. Любой рабочий вариант флагов пройдёт.
//
//   node 00-setup/labs/02-pick-the-flags/check.mjs
//   node 00-setup/labs/02-pick-the-flags/check.mjs --solution

import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { holds, labTarget, report } from '../../../tools/lab.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const probe = join(here, 'probe.mjs');

function run(extraFlags) {
  try {
    const output = execFileSync(process.execPath, [...extraFlags, probe], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      maxBuffer: 256 * 1024 * 1024,
    });
    return { ok: true, output };
  } catch (error) {
    return { ok: false, output: `${error.stdout ?? ''}${error.stderr ?? ''}`, error };
  }
}

const countOf = (text, pattern) => (text.match(pattern) ?? []).length;
const bytecodeHeaders = (text) => [...text.matchAll(/generated bytecode for function: (\w*)/g)].map((match) => match[1]);

const { flags } = await import(labTarget(import.meta.url, 'flags.mjs'));
const given = (name) => (Array.isArray(flags?.[name]) ? flags[name] : []);

// Базовые замеры без дополнительных флагов: относительно них проверяются цели 2, 3 и 5.
const baselineOptimization = run(['--trace-opt']).output;
const baselineScavenges = countOf(run(['--trace-gc']).output, /Scavenge/g);

const results = [];

{
  const { ok, output } = run(given('printOneBytecode'));
  const headers = new Set(bytecodeHeaders(output));
  const onlyHotLoop = headers.has('hotLoop') && [...headers].every((name) => name === 'hotLoop');
  results.push(
    holds(
      '1. байткод только hotLoop',
      ok && onlyHotLoop,
      !ok
        ? 'процесс упал'
        : headers.size === 0
          ? 'байткод не напечатан'
          : `напечатано функций: ${headers.size}`,
      'Нужны два флага: один включает печать байткода, другой ограничивает её одной функцией.',
    ),
  );
}

{
  const { ok, output } = run([...given('optimizeColdFunction'), '--trace-opt']);
  const optimizedNow = output.includes('<JSFunction hotLoop');
  const optimizedBefore = baselineOptimization.includes('<JSFunction hotLoop');
  results.push(
    holds(
      '2. hotLoop дошла до TurboFan',
      ok && optimizedNow && !optimizedBefore,
      !ok ? 'процесс упал' : optimizedNow ? 'без флагов она тоже оптимизируется' : 'в логе её нет',
      'Ищи флаг, который снимает порог горячести и оптимизирует всё подряд.',
    ),
  );
}

{
  const { ok, output } = run([...given('keepInInterpreter'), '--trace-opt']);
  const spinOptimized = output.includes('<JSFunction spin');
  const spinOptimizedBefore = baselineOptimization.includes('<JSFunction spin');
  results.push(
    holds(
      '3. spin осталась в интерпретаторе',
      ok && !spinOptimized && spinOptimizedBefore,
      !ok ? 'процесс упал' : spinOptimized ? 'spin всё ещё оптимизируется' : 'без флагов spin не оптимизируется — проверять нечего',
      'У V8 есть флаг с верхней границей уровня компиляции; ноль означает «только интерпретатор».',
    ),
  );
}

{
  const { ok, output } = run(given('showGarbageCollection'));
  const events = countOf(output, /Scavenge|Mark-Compact|Mark-Sweep/g);
  results.push(
    holds(
      '4. видны сборки мусора',
      ok && events > 0,
      !ok ? 'процесс упал' : `событий GC в выводе: ${events}`,
      'Самый прямой флаг из семейства --trace-*.',
    ),
  );
}

{
  const { ok, output } = run([...given('moreScavenges'), '--trace-gc']);
  const scavenges = countOf(output, /Scavenge/g);
  const enough = scavenges >= baselineScavenges * 1.5;
  results.push(
    holds(
      '5. scavenger срабатывает чаще',
      ok && enough,
      !ok ? 'процесс упал' : `${scavenges} против ${baselineScavenges} без флагов`,
      'Сборок станет больше, если молодому поколению уменьшить размер.',
    ),
  );
}

report('Лаба 00-2: подбери флаги', results);
